--vim.g.copilot_filetypes = {
--    ["*"] = false,
--    ["javascript"] = true,
--    ["javacriptreact"] = true,
--    ["typescriptreact"] = true,
--    ["bash"] = true,
--    ["typescript"] = true,
--    ["lua"] = false,
--    ["rust"] = true,
--    ["c"] = true,
--    ["c#"] = true,
--    ["c++"] = true,
--    ["go"] = true,
--    ["python"] = true,
--  }
--
--vim.g.copilot_no_tab_map = true

