require("famiclone.options")
require("famiclone.colors")
require("famiclone.keymap")
require("famiclone.lazy")
require("famiclone.netrw")
require("famiclone.themedev")
vim.cmd("source $HOME/.config/nvim/lua/famiclone/syntax.vim")
